
# @name authenticate
POST https://localhost:5001/connect/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Basic bmctc3RhcnRlci1jbGllbnQ6c2VjcmV0

username=alice
&password=Pass123$
&grant_type=password
&scope=openid profile accounts

###

@auth_token = {{authenticate.response.body.token_type}} {{authenticate.response.body.access_token}}

###

# @name get_user_info
GET https://localhost:5001/connect/userinfo
Authorization: {{auth_token}}
